# docker-compose.yml
version: '3.8'

services:
  # --- Serviço do Backend (API) ---
  backend:
    # INSTRUÇÃO: A imagem que você vai construir e enviar para o Docker Hub
    image: orickjogando/recrutamentoia-backend:latest
    networks:
      - Foco
    environment:
      # INSTRUÇÃO: Todas estas variáveis você deverá preencher na interface do Portainer.
      - NODE_ENV=production
      - FRONTEND_URL=${FRONTEND_URL}
      - VITE_BASEROW_API_KEY=${VITE_BASEROW_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - N8N_TRIAGEM_WEBHOOK_URL=${N8N_TRIAGEM_WEBHOOK_URL}
      - N8N_SCHEDULE_WEBHOOK_URL=${N8N_SCHEDULE_WEBHOOK_URL}
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=Foco"
        # INSTRUÇÃO: A linha abaixo foi corrigida para usar a URL correta do backend.
        - "traefik.http.routers.backend-router.rule=Host(`backend.recrutamentoia.com.br`)"
        - "traefik.http.routers.backend-router.entrypoints=websecure"
        - "traefik.http.routers.backend-router.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.backend-service.loadbalancer.server.port=3001"

  # --- Serviço do Frontend (React App) ---
  frontend:
    # INSTRUÇÃO: A imagem que você vai construir e enviar para o Docker Hub
    image: orickjogando/recrutamentoia-frontend:latest
    networks:
      - Foco
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=Foco"
        - "traefik.http.routers.frontend-router.rule=Host(`recrutamentoia.com.br`) || Host(`www.recrutamentoia.com.br`)"
        - "traefik.http.routers.frontend-router.entrypoints=websecure"
        - "traefik.http.routers.frontend-router.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.frontend-service.loadbalancer.server.port=80"

# --- Definição da Rede Externa 'Foco' ---
networks:
  Foco:
    external: true