# docker-compose.yml
# INSTRUÇÃO: Certifique-se de que a linha abaixo é a PRIMEIRA linha do seu arquivo, sem nenhum espaço antes.
version: '3.8'

services:
  # --- SERVIÇO DO TRAEFIK (PROXY REVERSO) ---
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    command:
      # --- Configurações do Traefik ---
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # --- Configurações do Let's Encrypt (Certificados SSL Automáticos) ---
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=contatorichardbittencourt@gmail.com" # <-- INSTRUÇÃO: SUBSTITUA 'SEU_EMAIL_AQUI@seudominio.com' PELO SEU E-MAIL REAL.
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - Foco # <-- ALTERADO

  # --- SERVIÇO DA SUA APLICAÇÃO (RECRUTA.AI) ---
  recruta-ai:
    build: .
    container_name: recruta-ai-app
    restart: always
    networks:
      - Foco # <-- ALTERADO
    environment:
      # INSTRUÇÃO: Todas estas variáveis você deverá preencher na interface do Portainer,
      # não diretamente neste arquivo.
      - NODE_ENV=production
      - FRONTEND_URL=${FRONTEND_URL}
      - VITE_BASEROW_API_KEY=${VITE_BASEROW_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - N8N_TRIAGEM_WEBHOOK_URL=${N8N_TRIAGEM_WEBHOOK_URL}
      - N8N_SCHEDULE_WEBHOOK_URL=${N8N_SCHEDULE_WEBHOOK_URL}
    labels:
      # --- Rótulos para o Traefik descobrir e configurar este serviço ---
      - "traefik.enable=true"

      # --- Roteador para redirecionar HTTP para HTTPS ---
      - "traefik.http.routers.recruta-ai-web.rule=Host(`recrutamentoia.com.br`) || Host(`backend.recrutamentoia.com.br`)"
      - "traefik.http.routers.recruta-ai-web.entrypoints=web"
      - "traefik.http.routers.recruta-ai-web.middlewares=redirect-to-https"

      # --- Middleware de redirecionamento ---
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

      # --- Roteador principal para tráfego HTTPS ---
      - "traefik.http.routers.recruta-ai-websecure.rule=Host(`recrutamentoia.com.br`) || Host(`backend.recrutamentoia.com.br`)"
      - "traefik.http.routers.recruta-ai-websecure.entrypoints=websecure"
      - "traefik.http.routers.recruta-ai-websecure.tls=true"
      - "traefik.http.routers.recruta-ai-websecure.tls.certresolver=myresolver"
      - "traefik.http.services.recruta-ai.loadbalancer.server.port=3001"

# --- Rede para comunicação entre o proxy e a aplicação ---
networks:
  Foco: # <-- ALTERADO
    driver: bridge